version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quick_commerce
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network

  eureka-server:
    build: ./Eureka-Server
    container_name: eureka-server
    restart: always
    environment:
      EUREKA_INSTANCE_HOSTNAME: eureka-server
      EUREKA_CLIENT_REGISTERWITHEUEREKA: "false"
      EUREKA_CLIENT_REGISTERWITHEUREKA: "false"
      EUREKA_CLIENT_FETCHREGISTRY: "false"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    ports:
      - "8761:8761"
    networks:
      - my-network

  api-gateway:
    build: ./API-Gateway
    container_name: api-gateway
    restart: always
    depends_on:
      - mysql-db
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/quick_commerce
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      EUREKA_INSTANCE_PREFERIPADDRESS: "true"
      EUREKA_INSTANCE_HOSTNAME: api-gateway
      SPRING_CLOUD_GATEWAY_ROUTES[0]_ID: auth-service
      SPRING_CLOUD_GATEWAY_ROUTES[0]_URI: http://auth-service:8081
      SPRING_CLOUD_GATEWAY_ROUTES[0]_PREDICATES[0]: Path=/auth-service/api/**
      SPRING_CLOUD_GATEWAY_ROUTES[0]_FILTERS[0]: StripPrefix=1
    ports:
      - "8080:8080"
    networks:
      - my-network

  auth-service:
    build: ./Auth-Service
    container_name: auth-service
    restart: always
    depends_on:
      - mysql-db
      - eureka-server
      - user-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/quick_commerce
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      EUREKA_INSTANCE_PREFERIPADDRESS: "true"
      EUREKA_INSTANCE_HOSTNAME: auth-service
      USER-SERVICE_RIBBON_LISTOFSERVERS: user-service:8086
      FEIGN_CLIENT_CONFIG_DEFAULT_URL: http://user-service:8086
    ports:
      - "8081:8081"
    networks:
      - my-network

  user-service:
    build: ./User-Service
    container_name: user-service
    restart: always
    depends_on:
      - mysql-db
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/quick_commerce
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      EUREKA_INSTANCE_PREFERIPADDRESS: "true"
      EUREKA_INSTANCE_HOSTNAME: user-service
      SPRING_APPLICATION_NAME: USER-SERVICE
    ports:
      - "8086:8086"
    networks:
      - my-network

  product-service:
    build: ./Product-Service
    container_name: product-service
    restart: always
    depends_on:
      - mysql-db
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/quick_commerce
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      EUREKA_INSTANCE_PREFERIPADDRESS: "true"
      EUREKA_INSTANCE_HOSTNAME: product-service
    ports:
      - "8082:8082"
    networks:
      - my-network

  inventory-service:
    build: ./Inventory-Service
    container_name: inventory-service
    restart: always
    depends_on:
      - mysql-db
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/quick_commerce
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      EUREKA_INSTANCE_PREFERIPADDRESS: "true"
      EUREKA_INSTANCE_HOSTNAME: inventory-service
    ports:
      - "8083:8083"
    networks:
      - my-network

  payment-service:
    build: ./Payment-Service
    container_name: payment-service
    restart: always
    depends_on:
      - mysql-db
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/quick_commerce
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      EUREKA_INSTANCE_PREFERIPADDRESS: "true"
      EUREKA_INSTANCE_HOSTNAME: payment-service
    ports:
      - "8085:8085"
    networks:
      - my-network

  order-service:
    build: ./Order-Service
    container_name: order-service
    restart: always
    depends_on:
      - mysql-db
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/quick_commerce
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      EUREKA_INSTANCE_PREFERIPADDRESS: "true"
      EUREKA_INSTANCE_HOSTNAME: order-service
    ports:
      - "8084:8084"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local 