version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quick_commerce
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network

  eureka-server:
    build: ./Eureka-Server
    container_name: eureka-server
    restart: always
    ports:
      - "8761:8761"
    networks:
      - my-network

  api-gateway:
    build: ./API-Gateway
    container_name: api-gateway
    restart: always
    depends_on:
      - mysql-db
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/quick_commerce
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    ports:
      - "8080:8080"
    networks:
      - my-network

  auth-service:
    build: ./Auth-Service
    container_name: auth-service
    restart: always
    depends_on:
      - mysql-db
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/quick_commerce
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    ports:
      - "8081:8081"
    networks:
      - my-network

  user-service:
    build: ./User-Service
    container_name: user-service
    restart: always
    depends_on:
      - mysql-db
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/quick_commerce
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    ports:
      - "8082:8082"
    networks:
      - my-network

  product-service:
    build: ./Product-Service
    container_name: product-service
    restart: always
    depends_on:
      - mysql-db
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/quick_commerce
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    ports:
      - "8083:8083"
    networks:
      - my-network

  inventory-service:
    build: ./Inventory-Service
    container_name: inventory-service
    restart: always
    depends_on:
      - mysql-db
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/quick_commerce
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    ports:
      - "8084:8084"
    networks:
      - my-network

  payment-service:
    build: ./Payment-Service
    container_name: payment-service
    restart: always
    depends_on:
      - mysql-db
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/quick_commerce
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    ports:
      - "8085:8085"
    networks:
      - my-network

  order-service:
    build: ./Order-Service
    container_name: order-service
    restart: always
    depends_on:
      - mysql-db
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/quick_commerce
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    ports:
      - "8086:8086"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local 