name: Quickmart Backend CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Grant execute permissions to mvnw
      run: find . -name "mvnw" -exec chmod +x {} \;
      
    - name: Build Auth Service
      run: cd Auth-Service && ./mvnw clean package -DskipTests
        
    - name: Build Eureka Server
      run: cd Eureka-Server && ./mvnw clean package -DskipTests
        
    - name: Build API Gateway
      run: cd API-Gateway && ./mvnw clean package -DskipTests
        
    - name: Build Inventory Service
      run: cd Inventory-Service && ./mvnw clean package -DskipTests
        
    - name: Build Order Service
      run: cd Order-Service && ./mvnw clean package -DskipTests
        
    - name: Build Payment Service
      run: cd Payment-Service && ./mvnw clean package -DskipTests
        
    - name: Build Product Service
      run: cd Product-Service && ./mvnw clean package -DskipTests
        
    - name: Build User Service
      run: cd User-Service && ./mvnw clean package -DskipTests

  test:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Test Auth Service
      run: cd Auth-Service && ./mvnw test
        
    - name: Test Eureka Server
      run: cd Eureka-Server && ./mvnw test
        
    - name: Test API Gateway
      run: cd API-Gateway && ./mvnw test
        
    - name: Test Inventory Service
      run: cd Inventory-Service && ./mvnw test
        
    - name: Test Order Service
      run: cd Order-Service && ./mvnw test
        
    - name: Test Payment Service
      run: cd Payment-Service && ./mvnw test
        
    - name: Test Product Service
      run: cd Product-Service && ./mvnw test
        
    - name: Test User Service
      run: cd User-Service && ./mvnw test

  docker-build-push:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
        
    - name: Build and push Auth Service Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./Auth-Service
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/quickmart-auth-service:latest
        
    - name: Build and push Eureka Server Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./Eureka-Server
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/quickmart-eureka-server:latest
        
    - name: Build and push API Gateway Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./API-Gateway
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/quickmart-api-gateway:latest
        
    - name: Build and push Inventory Service Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./Inventory-Service
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/quickmart-inventory-service:latest
        
    - name: Build and push Order Service Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./Order-Service
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/quickmart-order-service:latest
        
    - name: Build and push Payment Service Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./Payment-Service
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/quickmart-payment-service:latest
        
    - name: Build and push Product Service Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./Product-Service
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/quickmart-product-service:latest
        
    - name: Build and push User Service Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./User-Service
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/quickmart-user-service:latest 
