name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [Eureka-Server, Auth-Service, Inventory-Service, Product-Service, User-Service, Payment-Service, Order-Service, Api-Gateway]

    steps:
      - name: Grant execute permissions to mvnw
        run: chmod +x ${{ matrix.service }}/mvnw
        
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: 23
          distribution: 'temurin'
          cache: maven

      - name: Build and Test ${{ matrix.service }}
        working-directory: ${{ matrix.service }}
        run: ./mvnw clean install -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image - ${{ matrix.service }}
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/quickmart-${{ matrix.service }}:latest
            ${{ secrets.DOCKER_USERNAME }}/quickmart-${{ matrix.service }}:${{ github.sha }} 
